services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HTTP_PROXY: ${HTTP_PROXY:-}
        HTTPS_PROXY: ${HTTPS_PROXY:-}
        NO_PROXY: ${NO_PROXY:-}
    container_name: matrikkel_app
    ports:
      - "8083:80"
    volumes:
      - .:/var/www/html
      - ./var:/var/www/html/var
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - SYMFONY_ENV=dev
      - SYMFONY_DEBUG=1
      - MATRIKKELAPI_ENVIRONMENT=${MATRIKKELAPI_ENVIRONMENT:-prod}
      - MATRIKKELAPI_LOGIN=${MATRIKKELAPI_LOGIN:-your_login}
      - MATRIKKELAPI_PASSWORD=${MATRIKKELAPI_PASSWORD:-your_password}
      - HTTP_PROXY=${HTTP_PROXY:-}
      - HTTPS_PROXY=${HTTPS_PROXY:-}
      - NO_PROXY=${NO_PROXY:-}
    working_dir: /var/www/html
    depends_on:
      - composer
    networks:
      - matrikkel_network

  composer:
    image: composer:2
    container_name: matrikkel_composer
    volumes:
      - .:/app
    working_dir: /app
    command: ["composer", "install", "--no-dev", "--optimize-autoloader"]
    networks:
      - matrikkel_network

networks:
  matrikkel_network:
    driver: bridge

volumes:
  matrikkel_data: