# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
#    App\:
#        resource: '../src/'
#        exclude:
#            - '../src/DependencyInjection/'
#            - '../src/Entity/'
#            - '../src/Kernel.php'

    Iaasen\Matrikkel\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Client/MatrikkelTypes.php'

#    Iaasen\Matrikkel\Service\SoapClient:
#        factory: [ 'Iaasen\Matrikkel\Service\SoapClientFactory', 'create' ]
#        arguments: []

    Iaasen\Matrikkel\Client\AdresseClient:
        factory: [ Iaasen\Matrikkel\Client\SoapClientFactory, create ]
        arguments: [ Iaasen\Matrikkel\Client\AdresseClient ]
    Iaasen\Matrikkel\Client\BruksenhetClient:
        factory: [ Iaasen\Matrikkel\Client\SoapClientFactory, create ]
        arguments: [ Iaasen\Matrikkel\Client\BruksenhetClient ]
    Iaasen\Matrikkel\Client\BygningClient:
        factory: [ Iaasen\Matrikkel\Client\SoapClientFactory, create ]
        arguments: [ Iaasen\Matrikkel\Client\BygningClient ]
    Iaasen\Matrikkel\Client\KommuneClient:
        factory: [ Iaasen\Matrikkel\Client\SoapClientFactory, create ]
        arguments: [ Iaasen\Matrikkel\Client\KommuneClient ]
    Iaasen\Matrikkel\Client\StoreClient:
        factory: [ Iaasen\Matrikkel\Client\SoapClientFactory, create ]
        arguments: [ Iaasen\Matrikkel\Client\StoreClient ]
    Iaasen\Matrikkel\Client\MatrikkelenhetClient:
        factory: [ Iaasen\Matrikkel\Client\SoapClientFactory, create ]
        arguments: [ Iaasen\Matrikkel\Client\MatrikkelenhetClient ]
    Iaasen\Matrikkel\Client\PersonClient:
        factory: [ Iaasen\Matrikkel\Client\SoapClientFactory, create ]
        arguments: [ Iaasen\Matrikkel\Client\PersonClient ]

    # Laminas DB Adapter configuration
    #Laminas\Db\Adapter\Adapter:
    #    arguments:
    #        -   driver: 'Pdo_Sqlite'
    #            database: '%kernel.project_dir%/var/database.sqlite'

    # PostgreSQL configuration example (uncomment and configure for PostgreSQL)
    Laminas\Db\Adapter\Adapter:
        arguments:
            -   driver: 'Pdo_Pgsql'
                database: '%env(DB_NAME)%'
                hostname: '%env(DB_HOST)%'
                port: '%env(int:DB_PORT)%'
                username: '%env(DB_USERNAME)%'
                password: '%env(DB_PASSWORD)%'

    # Repository Services for PostgreSQL Database Access
    Iaasen\Matrikkel\LocalDb\AdresseRepository:
        arguments:
            $dbHost: '%env(DB_HOST)%'
            $dbPort: '%env(DB_PORT)%'
            $dbName: '%env(DB_NAME)%'
            $dbUsername: '%env(DB_USERNAME)%'
            $dbPassword: '%env(DB_PASSWORD)%'

    Iaasen\Matrikkel\LocalDb\MatrikkelenhetRepository:
        arguments:
            $dbHost: '%env(DB_HOST)%'
            $dbPort: '%env(DB_PORT)%'
            $dbName: '%env(DB_NAME)%'
            $dbUsername: '%env(DB_USERNAME)%'
            $dbPassword: '%env(DB_PASSWORD)%'

    Iaasen\Matrikkel\LocalDb\BygningRepository:
        arguments:
            $dbHost: '%env(DB_HOST)%'
            $dbPort: '%env(DB_PORT)%'
            $dbName: '%env(DB_NAME)%'
            $dbUsername: '%env(DB_USERNAME)%'
            $dbPassword: '%env(DB_PASSWORD)%'

    Iaasen\Matrikkel\LocalDb\BruksenhetRepository:
        arguments:
            $dbHost: '%env(DB_HOST)%'
            $dbPort: '%env(DB_PORT)%'
            $dbName: '%env(DB_NAME)%'
            $dbUsername: '%env(DB_USERNAME)%'
            $dbPassword: '%env(DB_PASSWORD)%'

    Iaasen\Matrikkel\LocalDb\KommuneRepository:
        arguments:
            $dbHost: '%env(DB_HOST)%'
            $dbPort: '%env(DB_PORT)%'
            $dbName: '%env(DB_NAME)%'
            $dbUsername: '%env(DB_USERNAME)%'
            $dbPassword: '%env(DB_PASSWORD)%'

    Iaasen\Matrikkel\LocalDb\PersonRepository:
        arguments:
            $dbHost: '%env(DB_HOST)%'
            $dbPort: '%env(DB_PORT)%'
            $dbName: '%env(DB_NAME)%'
            $dbUsername: '%env(DB_USERNAME)%'
            $dbPassword: '%env(DB_PASSWORD)%'

    # PDO service for direct database access
    PDO:
        class: PDO
        factory: ['Iaasen\Matrikkel\Service\PdoFactory', 'create']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
